# sc_rankingの設定ファイル
# 複数のスコアボードペアを設定できます

# 旧形式の設定（シングルペア用・後方互換性のため）
base: points
paste: ranking

pairs:
  example1:
    base: points
    paste: ranking

  example2:
    base: killCount
    paste: killRanking
